### PR TITLE
Added support for setting the "delimited" parameter.

### PR DESCRIPTION
**Pull request by ghost**
Hi, I will like to contribute code for supporting the "delimited" parameter: http://dev.twitter.com/pages/streaming_api_methods#delimited

To use this mode you need to set the TwitterStreamProcessor to be a DelimitedTwitterStreamProcessor and  override the processTwitterUpdate method:

```
new DelimitedTwitterStreamProcessor() {
    public void processTwitterUpdate(byte[] bytes, String credentials,
                                     HashSet<String> ids)
      throws InterruptedException, IOException {
        System.out.print(new String(bytes, "UTF-8"));
    }
  }
```

Also, you have to set the delimited parameter to true:

```
TwitterClient tc = new TwitterClient(...);
tc.setDelimited(true);
...
tc.execute();
```

Please let me know what you think about it.

### CODE REVIEW

**Comment by tommay** [comment]
Elmer,

Thanks for doing this.  I dropped in a few comments in one or two of the files.  Would you mind making the style match the rest of the code?  Mostly four space indent with no tabs.

Thanks,
Tom

**Comment by bigdata-mx** [comment]
Hi Tom, 

I have commited the files with the requested changes.

Thank you, 

Elmer

**Comment by tommay** [comment]
Thanks.  Please be patient :-)

One quick comment: hoisting the "new DataInputStream" outside the loop may be sketchy.  When I thought about it, using DataInputStream.readFully at all may also be sketchy.  But I checked the contract for DataInput.readFully which says:

```
 * Reads some bytes from an input
 * stream and stores them into the buffer
 * array <code>b</code>. The number of bytes
 * read is equal
 * to the length of <code>b</code>.
```

In particular, saying "the number of bytes _read_ is equal to the length of b" seems to make it safe here.  I was concerned that it may read more bytes than it stores, even though I can't think of any good reason why an implementation would do that.  But the contract says it's not supposed to do that.

Are you running the delimited code and having it work for you?  Just curious.

I was also thinking that having to pass delimited=true to the constructor (or use a setter) is not as robust as calling a method on the TwitterStreamProcessor to ask it whether it requires a delimited stream or not.

We could have two abstract classes, your DelimitedTwitterStreamProcessor with say a boolean wantsDelimitedStream method that returns true, and an UndelimitedTwitterStreamProcessor with a method that returns false.

What do you think?  If it sounds ok, would you like to code things up that way?

Thanks,
Tom

**Comment by tommay** [comment]
wantsDelimitedStream would be a new method on interface TwitterStreamProcessor, in case that wasn't clear, with the appropriate implementation in the abstract classes.

**Comment by bigdata-mx** [comment]
Hi, 

> I was concerned that it may read more bytes than it stores, even though I can't think of any good reason why an implementation would do that. But the contract says it's not supposed to do that.

That's right as far as I know that is the way DataInputStream works, in contrast with BufferedReader or BufferedInputStream that may consume bytes from the raw stream in advance. That's why we use a special readLine() method not the one in BufferedReader.

> Are you running the delimited code and having it work for you? Just curious.

Yes, I have been running the delimited code for a few days with out errors.

> What do you think? If it sounds ok, would you like to code things up that way?

It sounds ok, in this way it won't break the compatibility with previous versions. 

Do you think that an UndelimitedTwitterStreamProcessor should exist or we should let this to the implementor of the interface as is currently done with TwitterStreamProcessor? 

Elmer

**Comment by tommay** [comment]
I don't care about breaking things as much as I care about doing things in nice ways that I wouldn't mind people coying :-)  Adding a method to the interface will break things.  But it will break things catastrophically so that's ok.

I think a new abstract class would be fine, with just the wantsDelimitedStream or whatever method defined.  I can do it if you'd rather, if you're not sure what I'm talking about.

**Comment by bigdata-mx** [comment]
You are right. Don't worry I got the idea, I'll notify you when the changes are ready.

**Comment by bigdata-mx** [comment]
Tom, the changes are already in the fork.

Elmer

**Comment by tommay** [comment]
Thanks!  I'll have a look and pull and if anything needs a tweak I'll make it.

**Pull request merged**
